namespace MathProblems {  
  /**
   * Individual math problem to solve. Generated by ProblemSet. 
   *
   * @class Problem
   */
  export class Problem {
    constructor(operator: string, operands: Operand[]) {
      this.Operator = operator;
      this.Operands = operands;
      this.WrongAttempts = [];
      this.OperandsGenerated = Operand.resolveOperands(this.Operands);
      this.Answer = this.getAnswer();
    }

    public Operator: string; // + - / *  
    private Operands: Operand[];
    public Answer?: number;
    public WrongAttempts: number[];


    private OperandsGenerated: number[];


    public Generate(): string {
      let problem = "";
      let operands = this.OperandsGenerated;
      problem = operands.join(this.Operator);
      return problem;
    }



    public getSum(): number {
      const sum = this.OperandsGenerated.reduce(
        function (a, b) {
          return a + b
        }, 0
      );
      return sum;
    }



    public getAnswer(): number | undefined {
      let answer: number | undefined;
      if (this.Operator === "+") {
        answer = this.getSum();
      }
      else {
        // something here.
      }
      return answer;
    }
  }
}